### ISSUE TITLE
Structure is not generated (village, temple, etc) with Forge 2705

### ISSUE THREAD

**Issue by HawkEye1015** [superfluke/hexlands#1]
I'm using locate command and go to this coordinates.
but village was not generated
[https://imgur.com/a/ys2cjBJ](https://imgur.com/a/ys2cjBJ)

I'm not editing config

**Comment by superfluke** [comment]
They do generate, but the locate command doesn't seem to be working properly. I'll have to look into it, thanks for the report.

**Comment by HawkEye1015** [comment]
I notice that the locate command dose not work.
I using Forge version is 2705,
but this mod created by forge of version is 2655.
The following images were I tried with each version
[https://imgur.com/vpIzMD0](https://imgur.com/vpIzMD0)
2655
[https://imgur.com/7D5gOXR](https://imgur.com/7D5gOXR)
2705
This bug seems to be caused by a different version.
