### ISSUE TITLE
Cannot craft a nether portal

### ISSUE THREAD

**Issue by Stereonoise** [superfluke/hexlands#11]
When i create a nether portal and try to light it nothing happens. I've tried in single player and creative. When i disabled just hex lands and play without the mod I can create a portal perfectly fine.

**Comment by superfluke** [comment]
I've tested this a few times on a couple forge version and never had a problem. Hex lands doesn't come anywhere near the nether portal code, so not totally sure whats going on here. Maybe there's some weird cross mod interaction going on, what forge version are you on and what other mods are you using?

**Comment by Stereonoise** [comment]
I'm using forge version 14.23.4.2705.
My mod list is;

- Aetherworks			
- Akashic Tome			
- AppleSkin			
- Astral Sorcery		
- AutoRegLib			
- B.A.S.E			
- Baubles			
- BdLib				
- BetterFps			
- BiblioCraft			
- Binnie's Mods			
- Career Bees			
- Chameleon			
- Chisel			
- Clumps			
- CodeChicken Lib 1.8.+		
- Comforts			
- ConnectedTexturesMod		
- Embers			
- Ender Storage 1.8.+		
- Fairy Lights			
- Familiar Fauna		
- FastWorkBench			
- Forestry			
- FTB Utilities			
- FTBLib			
- Gendustry			
- Hex Lands			
- Inventory Tweaks		
- Iron Chests			
- JEI Bees
- JourneyMap
- Just ENough Items(JEI)
- Just Enough Resources(JER)
- Magic Bees
- Mantle
- Morpheus
- Mystic World
- MysticLib
- Neat
- Psi
- Quark
- Quick Leaf Decay
- Redstone Flux
- Reliquary v1.3
- Roguelike Dungeons
- Roots
- SnowVillage
- Soot
- Storage Drawers
- Super Sound Muffler
- Thaumcraft
- Thaumcraft 6 Aspects for JEI
- Thaumic Inventory Scanning(Thaumcraft Addon)
- Thaumic JEI
- The One Probe
- Tinkers Construct
- Tinkers' Tool Leveling
- Tomb Many Graves 2
- TombManyGraves 2 API		
- Traverse

**Comment by superfluke** [comment]
Welp, thanks for the extra info, looks like it was my fault after all. Try turning off the 'forceHexGen' option and I'll have to look into why it's breaking nether portals.

**Comment by TheMCOne** [comment]
AppleSkin
ConnectedTexturesMod
Forestry
Iron Chests
JEI Bees
JourneyMap
Just Enough Items(JEI)
Super Sound Muffler
Thaumcraft
The One Probe
If it helps that is mod list I have in common with above

**Comment by superfluke** [comment]
forcedHexGen option has been removed for now until I can solve the bugs with it.
