### ISSUE TITLE
documentation for biomeHeightAdjustment ambiguous

### ISSUE THREAD

**Issue by bogger33** [superfluke/hexlands#12]
# How much biomes influence the final height of the hex

I think it's worth mentioning whether higher numbers increase or decrease height variation, like on the biomeSize setting

**Comment by superfluke** [comment]
Well it can do either. For example, forest hills might have a multiplier of 0.5 which will raise the base height by 0.5*biomeHeightAdjustment. But other biomes have negative multipliers. Rivers have a multiplier of about -0.3 so the final height is going to be -0.3*biomeHeightAdjustment, which will be lower than the baseline. 

If you can think of a way to make that more clear, I'm willing to take suggestions.

**Comment by bogger33** [comment]
i would suggest doing it like this instead, unless there's something I'm not considering:

I would suggest having it either be a percentage, where 0% leaves the value exactly where it is, and any other percentage brings it that percentage of it's value closer to 0. So 100 makes all biomes exactly the same height, 80% would make the variation 80% less drastic, no matter whether the biomes are negative or positive, and how big their actual value is, it's always proportional.

alternatively have it be an absolute number, and move it that amount closer to 0. If there's overshoot, set the value to 0

**Comment by superfluke** [comment]
I feel like the suggestions might just be complicating things or restricting how much you can move the biomes compared to the current version. Tried rewording the config a bit so maybe its a bit more clear

**Comment by bogger33** [comment]
yeah like I said in my edit, I agree, I think I just got too stuck on this idea that the way to differentiate them has to be negatives and positives. I would still suggest explicitly mentioning that you want values between 0 and 1 if you want to decrease the amount of variation, though.
