### ISSUE TITLE
Mansion not in world

### ISSUE THREAD

**Issue by raltus** [superfluke/hexlands#17]
I was trying out the mod and while flying around looking at the generation from another mod I thought I'd see how a mansion generated in this one. I used the locate command and it came back with the not found message. After trying a couple other seeds I loaded a vanilla generation world and found a mansion with locate. I loaded the same seed with hex lands and got the same not found message. I also checked a cartographer and he didn't have the map as a trade. 
Going to the config I noticed it isn't listed in the structures. I don't know much about code and thought I would try adding in the missing lines into the config but it wouldn't save the addition, which I noticed after reopening it after trying a new world. Even if it had saved there may have to be something added to the mod itself to let them generate.

**Comment by superfluke** [comment]
Mansions should spawn normally in 1.6 now
