### ISSUE TITLE
Crash when generating world using grass paths as rim blocks

### ISSUE THREAD

**Issue by DWX12** [superfluke/hexlands#20]
Wanted to use grass paths as rim blocks, but the world crashed when trying to generate. Might have something to do with trying to generate all the way to bedrock since I also have that option selected. Probably due to every block trying to update at once.

https://paste.dimdev.org/ujehatedoy.mccrash

**Comment by superfluke** [comment]
Yes probably too many updates from the grass paths. Best I can do is suggest not using blocks that cause lots of updates for the rim blocks.
