### ISSUE TITLE
[Request] Catan mode

### ISSUE THREAD

**Issue by DWX12** [superfluke/hexlands#21]
So there are two similar requests, one for islands and another for more control over biomes. What I'm wanting to do is recreate a Catan board, but with options for adding more hex tiles if I want (closer to the Seafarers expansion).

What would be needed is to be able to set the maximum number of a set list of biomes allowed while having another list of biomes that would be used as the remaining biomes, which would be ocean or deep ocean if you're looking at a Catan board. In addition, there would need to be some sort of biome count to set so a player could set how many hexs of a specified biome shows up. To further explain, a player could define set one of biomes to be: extreme hills, plains, mesa, forest, roofed forest, and desert. The second set would be set to: ocean and deep ocean. This would mean that any biome that doesn't show up in set one defaults to a biome in set two.

It might already work this way, but I'd like to see only oceans boarding hexs that are not an ocean type biome and deep ocean biomes only boarder other ocean biomes.

I'm hoping that you can add these options in some fashion.

Thanks for such an awesome mod, all of your hard work, and being a part of the community.

**Comment by erindalc** [comment]
What hex borders what hex is totally random based on my current findings.

I'm currently looking into seeing if I can accomplish some of what you're talking about using this and BiomeTweaker, although I haven't confirmed they're even compatible yet.

**Comment by erindalc** [comment]
That was super informative, thank you

**Comment by DWX12** [comment]
Thanks for all the information and for the assistance.
