### ISSUE TITLE
[Request] A few config options

### ISSUE THREAD

**Issue by thetakodev** [superfluke/hexlands#22]
Hello!
Please implement a few of these config options:
- a boolean to force disable borders on wet hexagons, because i want to have all land tiles split even if they are same, but not the wet ones
- config to set the wet tiles
- config to stop generating tiles after a certain amount of blocks, and just generate one biome (eg deepocean) (so it forms a huge hexagon made out of small ones)
- config to set how common is ocean biome is.
- disable rivers and beaches

**Comment by thetakodev** [comment]
I have implemented the first feature in my fork

**Comment by superfluke** [comment]
I can take a look at the first couple points but things like how common oceans are or disabling biomes are outside the scope of this mod. You can check out Some Like It Dry for some of those features.

**Comment by thetakodev** [comment]
Some Like It Dry doesn't seem to be compatible with bophex

**Comment by thetakodev** [comment]
![image](https://user-images.githubusercontent.com/32229391/44958927-895c3500-aee7-11e8-8e85-b2f2a191e401.png)
So imagine generating big hexagon(like on the image) but with significantly bigger sizes (1024x1024 chunks for example) and then everything else is deep deep ocean, basically making a continent

**Comment by thetakodev** [comment]
Also it would be great if the biomes (including BoP) were generated randomly, without taking humidity/temperature in account

**Comment by thetakodev** [comment]
Also get discord, its awesome

**Comment by superfluke** [comment]
Yeah some likes it dry isn't compatible with BoP. But I'm pretty sure BoP has it's own "use less oceans" config. Also if you want the biomes to be more random try setting the biomeSize to 2000 in the configs
https://discord.gg/BEM8ybb
