### ISSUE TITLE
BOP + Traverse Compatibility Issue

### ISSUE THREAD

**Issue by SextupleTap** [superfluke/hexlands#26]
When you have both Traverse and BOP installed at the same time, hex lands stops generating BOP Biomes even when BOP Hexlands is selected as the terrain generator. 
This occurs with the following combination of mod versions:

- BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar
- Traverse v1.6.0 build69 for 1.12.2
- hexlands-1.8.1.jar

**Comment by SextupleTap** [comment]
Just gonna push this through again o.0
Biomes o plenty biomes are not spawning when BOP Hexlands is selected while traverse is also installed.

**Comment by superfluke** [comment]
Just tested with:
BiomesOPlenty-1.12.2-7.0.1.2391
Traverse-1.12.2-1.6.0-69
hexlands-1.8.1
Using world type BoP Hexlands and had both BoP and traverse biomes show up. The mod versions you're using should be fine, so try deleting both BoP and traverse configs and letting them regenerate when making a new world.
