### ISSUE TITLE
Configs seems to be ignored

### ISSUE THREAD

**Issue by Maxiride** [superfluke/hexlands#8]
What can reproduce the issue:

- New instance with Hexlands only (of course forge present)
- Generate new world
- Change config values: tried to change hexSize to 50, 100, 5000 (Notepad++)
- Move to new chunks, nothing is changed
- Reboot client, check that configs haven't been overwritten by the mod (they aren't)
- New world, nothing changed.

I don't know what else I could provide to help debugging the issue honestly.

**Comment by UpcraftLP** [comment]
are you sure you saved the config after editing?
I tried with the latest code on github ([2933db3](https://github.com/superfluke/hexlands/commit/2933db3ddfdbaff3a7da1dbd546f962ebbcb8e21)) and it worked.

**Comment by Maxiride** [comment]
Yeah I always saved, turns out with a bit more or testing that somehow the issue is related to the worlds having the same name. I just spammed create new world->hexlands->go now that I deleted all the saves and made a new world again the config took place .
